[project]
name = "langchain-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "chromadb>=1.5.9",
    "grandalf>=0.8",
    "huggingface-hub>=1.28.0",
    "langchain>=1.3.16",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.0",
    "langchain-huggingface>=1.2.2",
    "langchain-ollama>=1.1.0",
    "notebook>=7.6.2",
    "numpy>=2.5.2",
    "pydantic>=2.13.4",
    "pypdf>=6.16.1",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=6.0.0",
    "streamlit>=1.62.0",
    "tiktoken>=0.14.0",
    "torch>=2.13.0",
    "transformers>=5.15.1",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]
torchvision = [{ index = "pytorch-cpu" }]
